# Cloudflare Pages configuration
name = "ourgoal"
compatibility_date = "2024-01-15"

# Pages build configuration
pages_build_output_dir = "dist"

[env.production]
# Production environment variables will be set in Cloudflare dashboard

[env.preview]
# Preview environment variables will be set in Cloudflare dashboard
