// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Missing Supabase environment variables. Please check your .env file.');
}

export const supabase = createClient<Database>(
  SUPABASE_URL as string, 
  SUPABASE_PUBLISHABLE_KEY as string, 
  {
    auth: {
      persistSession: true, // Make sessions persist in localStorage
      autoRefreshToken: true, // Automatically refresh the token before it expires
      storageKey: 'almoadela-qiyas-auth', // Custom storage key
    },
  }
);
