// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upucoktebmehokwamavi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwdWNva3RlYm1laG9rd2FtYXZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MDk0NTQsImV4cCI6MjA2MTI4NTQ1NH0.9rMk6-rC_uqQAfA8EyxDr0A72qoQS5qfOqIVTs3Gd2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true, // Make sessions persist in localStorage
    autoRefreshToken: true, // Automatically refresh the token before it expires
    storageKey: 'almoadela-qiyas-auth', // Custom storage key
  },
});
